### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by robmarkcole** [adafruit/Adafruit_CircuitPython_AMG88xx#12]
HI
had this working fine a day ago, now I am getting an error when calling `amg.pixels`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_amg88xx.py", line 164, in pixels
  File "adafruit_amg88xx.py", line 160, in pixels
  File "adafruit_bus_device/i2c_device.py", line 115, in write
OSError: [Errno 5] Input/output error
```

Any advice on debugging?

**Comment by robmarkcole** [comment]
I think this is just due to some dodgy wiring
