### ISSUE TITLE
error when run the camera example.

### ISSUE THREAD

**Issue by FPSychotic** [adafruit/Adafruit_CircuitPython_AMG88xx#30]
Hi, thanks by the great git and sharing. Im getting this error with camera example but the terminal example works ok. I had a difficult installation of pygame , Raspberry 4 with ubuntu 18.04 maybe that help to debug:

` python3 rpi_thermal_cam.py
pygame 2.0.0 (SDL 2.0.8, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
dbus[12339]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted
`
EDIT, IT WORKED FINALLY WITH SUDO BUT IT WILL CLOSE AND SEND A ERROR OR NEED REBOOT, It sends this msg
`Traceback (most recent call last):                               
  File "./rpi_thermal.py", line 80, in <module>
    for row in SENSOR.pixels:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/adafruit_amg88xx.py", line 167, in pixels
    i2c.write_then_readinto(buf, buf, out_end=1, in_start=1)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/adafruit_bus_device/i2c_device.py", line 149, in write_then_readinto
    in_end=in_end,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/busio.py", line 141, in writeto_then_readfrom
    stop=stop,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 88, in writeto_then_readfrom
    address, buffer_out[out_start:out_end], in_end - in_start
  File "/home/ubuntu/.local/lib/python3.6/site-packages/Adafruit_PureIO/smbus.py", line 273, in read_i2c_block_data
    ioctl(self._device.fileno(), I2C_RDWR, request)
OSError: [Errno 5] Input/output error
`

**Comment by FPSychotic** [comment]
Ok it looks the code was duplicated in the file  forget it and take care
